- client-app/src/common/services/initialization.service.ts
- layout/theme.liquid
- locales/en.default.json
- templates/404.liquid
- templates/500.liquid
- templates/accessdenied.liquid
- templates/customers/login.liquid
- templates/index.liquid
404:
500 (in production):
500 (on dev):
Access denied:
> VP-1482: server side error handling

- client-app/src/pages/account/store/modules/orders-list/actions.ts
- client-app/src/pages/account/store/modules/orders-list/index.ts
- client-app/src/pages/account/store/modules/orders-list/types.ts
- client-app/src/pages/account/views/AccountOrders.vue
> Implement Orders server side sorting and row selection

- client-app/src/pages/account/store/modules/orders-list/index.ts
- locales/de.json
- locales/en.default.json
Error was fixed. The wrong field(column key) name was corrected.
> VP-1498 display money (according to platform currencies settings)

- client-app/src/common/constants.ts
- layout/login.liquid
- locales/de.json
- locales/en.default.json
- templates/customers/forgot_password.liquid
- templates/customers/login.liquid
- templates/customers/reset_password.liquid
- templates/customers/reset_password_confirmation.liquid
Add validation on submit
Makeup styles to more prettier
Success message on submit for "forgot password" and  "reset password" forms
Change page sizes constant
> VP-1531 Make up forgotpassword and resetpassword

- client-app/src/common/services/initialization.service.ts
- client-app/src/pages/account/components/order-details/OrderDetailsItem.vue
- client-app/src/pages/account/components/order-details/OrderDetailsTotals.vue
- client-app/src/pages/account/store/modules/orders-list/actions.ts
- client-app/src/pages/account/store/modules/orders-list/definitions.ts
- client-app/src/pages/account/store/modules/orders-list/getters.ts
- client-app/src/pages/account/store/modules/orders-list/index.ts
- client-app/src/pages/account/store/modules/orders-list/mutations.ts
- client-app/src/pages/account/store/modules/orders-list/types.ts
- client-app/src/pages/account/views/AccountOrderDetailsModal.vue
- client-app/src/pages/account/views/AccountOrders.vue
- locales/de.json
- locales/en.default.json
> VP-1395: Implement order details feature

- templates/customers/reset_password_confirmation.liquid
Layout was fixed.
Login link`s localization was fixed.
> Fix "reset_password_confirmation" page

- client-app/src/common/api/api-clients.ts
Keyword was add to OrderSearchCriteria
> VP-1628 Regenerate API client

- client-app/package-lock.json
- client-app/package.json
- client-app/src/pages/account/store/modules/orders-list/index.ts
- client-app/src/pages/account/views/AccountOrders.vue
- locales/de.json
- locales/en.default.json
-Fix filters layout
-Fix status dropdown behaviour
-Show no-orders message inside empty table
> Improve order list page

- client-app/src/pages/account/views/AccountOrders.vue
- locales/de.json
- locales/en.default.json
Also the bug with Select All statues filter was fixed.
> VP-1497 Implement ability add/edit text before/after orders grid

- client-app/src/pages/account/store/modules/users-list/actions.ts
- client-app/src/pages/account/store/modules/users-list/definitions.ts
- client-app/src/pages/account/views/AccountUsers.vue
- client-app/src/pages/account/views/EditUserModal.vue
- locales/de.json
- locales/en.default.json
I also made PR to storefront to fix 500 error
> VP-1449: Implement ability to edit user

- client-app/src/common/api/api-clients.ts
Odrers payments api was added.
> VP-1407: Regenerate storefront API client

- client-app/src/pages/account/components/invoices-filter/index.vue
- client-app/src/pages/account/components/orders-filter/index.vue
- client-app/src/pages/account/components/payments-filter/index.vue
- client-app/src/pages/account/components/users-filter/index.vue
- client-app/src/pages/account/store/modules/orders-list/index.ts
- client-app/src/pages/account/store/modules/users-list/index.ts
- client-app/src/pages/account/views/account-invoices/index.vue
- client-app/src/pages/account/views/account-orders/index.vue
- client-app/src/pages/account/views/account-users/index.vue
- config/settings_data.json
- locales/de.json
- locales/en.default.json
* layout changes for order/user filters
* add const for startPageNumber
* remove currency from ammount column in invoice and payment pages
* change labels in filters
* change localization for 'no-data' message
* change date format in orders page
> VP-1701: Make UI improvements

- client-app/src/pages/account/views/account-invoices/index.vue
- client-app/src/pages/account/views/account-payments/index.vue
- client-app/src/pages/account/views/account-users/index.vue
> Add word-break to tables

- client-app/src/pages/account/router/index.ts
- layout/theme.liquid
> VP-1670: add showing page titles

- client-app/src/pages/account/views/account-order-details-modal/account-order-details-modal.ts
- client-app/src/pages/account/views/account-order-details-modal/index.vue
- client-app/src/pages/account/views/account-orders/account-orders.ts
- client-app/src/pages/account/views/account-orders/index.vue
> fix wrong pipeline of opening the order details

- layout/theme.liquid
https://virtocommerce.atlassian.net/browse/VP-1797
> VP-1797: hotfix dev

- layout/theme.liquid
Problem was in storefront`s bug
> VP-1797:  Revert the wrong fix

- client-app/src/pages/account/components/edit-user-modal/edit-user-modal.ts
- client-app/src/pages/account/components/edit-user-modal/index.vue
Error on user updating is still stending.
> VP-1784: Add validation of first name n last name to edit user from

- client-app/package-lock.json
- client-app/package.json
- client-app/src/common/models/dictionary.ts
- client-app/src/common/models/search/keyword-search-criteria.ts
- client-app/src/common/models/search/order-search-criteria.ts
- client-app/src/common/models/search/order-search-query.ts
- client-app/src/common/models/search/product-search-criteria.ts
- client-app/src/common/models/search/product-search-query.ts
- client-app/src/common/models/search/search-query.ts
- client-app/src/common/services/query-builder.service.ts
- client-app/src/pages/account/components/orders-filter/index.vue
- client-app/src/pages/account/components/orders-filter/orders-filter.ts
- client-app/src/pages/account/store/index.ts
- client-app/src/pages/account/store/modules/orders-list/actions.ts
- client-app/src/pages/account/store/modules/orders-list/definitions.ts
- client-app/src/pages/account/store/modules/orders-list/getters.ts
- client-app/src/pages/account/store/modules/orders-list/index.ts
- client-app/src/pages/account/store/modules/orders-list/mutations.ts
- client-app/src/pages/account/store/modules/orders-list/types.ts
- client-app/src/pages/account/store/mutations.ts
- client-app/src/pages/account/store/types.ts
- client-app/src/pages/account/views/account-orders/account-orders.ts
- client-app/src/pages/account/views/account-orders/index.vue
- client-app/src/plugins/authorization/authorization.plugin.ts
- client-app/tsconfig.json
VP-1815
Also include:
* Fix for checking administrator rights
* Fix for warnings about location in account orders
* Refactored account orders data store
* Refactored account order logic (`?:` to if-else and similar)
> Parse & build query for orders list in account

- client-app/src/pages/account/App.vue
- client-app/src/pages/account/router/index.ts
- client-app/src/pages/admin/index.vue
- client-app/src/pages/history/index.vue
- client-app/tsconfig.json
> Change Main Menu Structure

- client-app/src/core/services/initialization.service.ts
- client-app/src/libs/user/store/users-list/actions.ts
- client-app/src/libs/user/store/users-list/definitions.ts
- client-app/src/pages/account/views/account-users/account-users.ts
- client-app/src/pages/account/views/account-users/index.vue
- locales/de.json
- locales/en.default.json
- templates/lockedout.liquid
Video in comments: https://virtocommerce.atlassian.net/browse/VP-1391
> VP-1391: Implement ability to suspend/unsuspend user's account

- config/settings_data.json
- locales/de.json
- locales/en.default.json
> VP-1855: Change order draft table structure

- client-app/src/libs/shopping-cart/components/cart-header/index.vue
- client-app/src/libs/shopping-cart/components/change-item-quantity/index.vue
> VP-1595: Fix long name case in editDraftHeader and width of input in Firefox

- client-app/src/libs/shopping-cart/views/add-to-order-draft-button/add-to-order-draft-button.ts
- client-app/src/libs/shopping-cart/views/add-to-order-draft-button/index.vue
- locales/de.json
- locales/en.default.json
* Disable add to draft item if  product is alrady in the draft
* add title to "add to draft" button
* remove the devider if  drafts list is empty
> VP-1923: Make some improvements after testing

- client-app/nswag.json
- client-app/src/libs/order-draft/components/add-draft-modal/add-draft-modal.ts
- client-app/src/libs/order-draft/components/add-draft-modal/index.vue
- locales/de.json
- locales/en.default.json
+ fix path for nswag output
video in comments: https://virtocommerce.atlassian.net/browse/VP-1955
> VP-1955:  Add duplicate check to add draft form

- client-app/src/libs/shopping-cart/views/add-to-cart-button/add-to-cart-button.ts
- client-app/src/libs/shopping-cart/views/add-to-cart-button/index.vue
- client-app/src/libs/shopping-cart/views/add-to-order-draft-button/add-to-order-draft-button.ts
- client-app/src/libs/shopping-cart/views/add-to-order-draft-button/index.vue
- client-app/src/pages/catalog/main.ts
- client-app/src/pages/catalog/views/active-order-sidebar/index.vue
- snippets/content_header.liquid
- snippets/product-grid-item.liquid
- templates/collection.liquid
- templates/product.liquid
> VP-1923:  Add shopping cart/draft product adding  ability to the product page

- client-app/src/libs/user/components/edit-user-modal/edit-user-modal.ts
- client-app/src/libs/user/components/edit-user-modal/index.vue
- client-app/src/pages/account/views/account-users/account-users.ts
- client-app/src/pages/account/views/account-users/index.vue
- locales/de.json
- locales/en.default.json
+ hide delete,suspend actions from current user
+ add loader for edit-user form
> VP-1391: Add action tooltips for users page

- client-app/src/libs/shopping-cart/store/cart/actions.ts
- client-app/src/libs/shopping-cart/store/cart/definitions.ts
- client-app/src/pages/catalog/views/active-order-sidebar/active-order-sidebar.ts
- client-app/src/pages/catalog/views/active-order-sidebar/index.vue
- locales/de.json
- locales/en.default.json
Simple checkout with the confirmation via the modal dialog window.
> VP-1933: Implement the active order checkout

- client-app/src/libs/shopping-cart/components/cart-header/index.vue
- client-app/src/libs/shopping-cart/components/cart-summary/cart-summary.ts
- client-app/src/libs/shopping-cart/components/cart-summary/index.vue
- client-app/src/pages/catalog/views/active-order-sidebar/index.vue
- locales/de.json
- locales/en.default.json
VP-1998: Show carts items quantity same way into the menu header button and the right sidebar
> VP-2000: Hide unnecessary fields in the shopping cart sidebar

- client-app/src/core/api/api-clients.ts
- client-app/src/libs/order-draft/store/drafts-list/actions.ts
Becouse API of createing order by named cart was changed. "removeCart" paramete was added.
> VP-1933: Regenerate API client

- client-app/src/core/constants.ts
- client-app/src/shims-tsx.d.ts
- config/settings_data.json
- layout/theme.liquid
- rework of the features branch in the settings_data.json file
- added new constants of the feature states
> Initial implementation of the toggling features process

- client-app/src/core/filters/img-url.ts
- client-app/src/core/utilities/utilities.ts
Check if suffix already exists
> VP-2552: Improve imgUrl filter

- assets/static/filter-icons.svg
- client-app/src/libs/shopping-cart/views/add-to-order-draft-button/index.vue
- client-app/src/styles/override/_main.scss
- snippets/collection-sidebar.liquid
- snippets/product-grid-item.liquid
- Collapsable filters were added, 
- Login screen bugs were fixed on the desktop and mobile versions.
- All fields became rouned
> Collapsable filters added and bugs fixing

- README.md
Readme.md was updated with new theme screenshots
> VP-3401 Update README.md

- client-app/src/styles/override/_main.scss
Empty space and additional text on the right
> VP-3843 — Login screen bugs fixing

- client-app/nswag.json
- client-app/src/core/api/api-clients.ts
> VP-4163: Update API client

- templates/blocks/helpers/catalog-script.liquid
- templates/blocks/json-product-tiles.liquid
- limit products count for rendering
- display cart on page where it is necessary
> product block fixes

- .github/workflows/main.yml
Added sonar scan step
Added Create release step
> VP-6108: CI workflow refacrtoring
